# Generated by Django 4.1 on 2022-08-26 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('incidentID', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('incidentDetails', models.CharField(max_length=100)),
                ('incidentDateTime', models.DateTimeField(default=datetime.datetime(2022, 8, 26, 8, 7, 20, 519198))),
                ('incidentPriority', models.IntegerField(default=0)),
                ('incidentStatus', models.BooleanField(default=False)),
                ('reportName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.users')),
            ],
        ),
    ]
