# Generated by Django 4.1 on 2022-08-26 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_incidents_incidentdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incidentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 13, 40, 56, 536986)),
        ),
    ]
