# Generated by Django 4.1 on 2022-08-26 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_incidents_incidentdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incidentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 24, 2, 613880)),
        ),
    ]
