# Generated by Django 4.1 on 2022-08-26 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_incidents_incidentdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incidentDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
